# Makefile for the focaltech touchscreen drivers.


obj-$(CONFIG_TOUCHSCREEN_FTS_FT3658U)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT3658U)	+=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT3658U)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT3658U)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT3658U)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT3658U)   +=  focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT3658U)   +=  focaltech_test/


obj-$(CONFIG_TOUCHSCREEN_FTS_FT3658U)	+=  focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT3658U)   +=  focaltech_flash/



obj-$(CONFIG_TOUCHSCREEN_FTS_FT3658U)   +=  focaltech_i2c.o
obj-$(CONFIG_TOUCHSCREEN_FTS_FT3658U)   +=  focaltech_game.o
