#
# Makefile for fingerprint drivers
#
# Each configuration option enables a list of files.

obj-$(CONFIG_FOCALTECH_FINGERPRINT) += focaltech/
obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_GOODIX_CAPACIIVE_FINGERPRINT) += goodix_capcitive/
