# History 1.0 added by hailong.chen for task 7787483 on 2019-05-23
# History 2.0 added by hailong.chen for task 7805046 on 2019-05-25
obj-$(CONFIG_TCT_DEVICEINFO) += device-info.o get_boot_device_info.o boot-reason.o get_cpuinfo.o
#obj-$(CONFIG_MTK_ROBUST)	+=  robust.o
obj-$(CONFIG_TCT_UI_TURBO) += uiturbo.o
obj-$(CONFIG_TCT_STAT) += stat.o
obj-$(CONFIG_TCT_PERF) += perf.o
